### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by ralphlange** [areaDetector/ADGenICam#45]
Packaging ADGenICam for ITER's CODAC Core System, I found that there is no license file and the documentation also doesn't mention the license conditions.

EPICS Open License?

**Comment by MarkRivers** [comment]
I added a LICENSE file in the top-level directory.  Please let me know if this is sufficient.  Licensing is not my strong suit!

**Comment by ralphlange** [comment]
EPICS Open License it is.

I'm not a lawyer, either... Our QA tools were complaining about this. All quiet now. Thanks!
